export const LOADING_DATA = "LOADING_DATA";
export const DATA_LOADED = "DATA_LOADED";
export const DATA_LOAD_FAILED = "ON_DATA_FAILED";

export const ADD_SITE_CATEGORY = "ADD_SITE_CATEGORY";
export const UPDATE_SITE_CATEGORY = "UPDATE_SITE_CATEGORY";
export const DELETE_SITE_CATEGORY = "DELETE_SITE_CATEGORY";
export const MOVE_SITE_CATEGORY = "MOVE_SITE_CATEGORY";

export const ADD_SITE = "ADD_SITE";
export const DELETE_SITE = "DELETE_SITE";
export const UPDATE_SITE = "UPDATE_SITE";

export const ADD_TASK_CATEGORY = "ADD_TASK_CATEGORY";
export const UPDATE_TASK_CATEGORY = "UPDATE_TASK_CATEGORY";
export const DELETE_TASK_CATEGORY = "DELETE_TASK_CATEGORY";
export const MOVE_TASK_CATEGORY = "MOVE_TASK_CATEGORY";

export const ADD_TASK = "ADD_TASK";
export const DELETE_TASK = "DELETE_TASK";
export const UPDATE_TASK = "UPDATE_TASK";

export const UPDATE_TITLE = "UPDATE_TITLE";

